### ISSUE TITLE
[Foxy] rosidl_typesupport_fastrtps_cpp.so: LoadLibrary error while launch Navigation2 or Moveit2 on Yocto dunfill

### ISSUE THREAD

**Issue by rafaelhuang-intel** [ros2-gbp/rosidl_typesupport_fastrtps-release#4]
[Foxy] rosidl_typesupport_fastrtps_cpp.so: LoadLibrary error while launch Navigation2 or Moveit2 on Yocto dunfill

OS: Yocto Dunfill
meta-ros: foxy
rosidl-typesupport-fastrtps-cpp : 1.0.1-1

Navigation2 error log:
[navigation2_simulate_error_log_20200923_1.txt](https://github.com/ros2-gbp/rosidl_typesupport_fastrtps-release/files/5375398/navigation2_simulate_error_log_20200923_1.txt)

Moveit2 error log:
[foxy_moveit_launch_fail_on_yocto_20201013.txt](https://github.com/ros2-gbp/rosidl_typesupport_fastrtps-release/files/5375399/foxy_moveit_launch_fail_on_yocto_20201013.txt)

**Comment by clalancette** [comment]
In general, its not a good idea to open issues against the `ros2-gbp` repos; they aren't where active development happens.  You'll typically want to open issues against the source repository.  Because of that, I'm going to close this out.

For your actual problem, I will mention that Yocto isn't one of our supported platforms.  So you'll have to get community support for it.  So your best bet may be to start by opening a question on https://answers.ros.org, and if it turns out to be a bug, open an issue against the relevant source repository.

**Comment by herb-kuta-lge** [comment]
> I will mention that Yocto isn't one of our supported platforms.

Just to be clear: "Yocto" = "OpenEmbedded", which is a platform with Tier 3 support for Foxy -- see https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023. But if "our" means the "development team", then the statement is correct because the definition of Tier 3 support says: "The development team does not run the unit test suite or perform any other tests on platforms in Tier 3."
